// flow-typed signature: 9580a76d9c3c5faf1bc1334120fe3260
// flow-typed version: <<STUB>>/@fortawesome/react-native-fontawesome_v^0.3.0/flow_v0.176.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@fortawesome/react-native-fontawesome'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@fortawesome/react-native-fontawesome' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@fortawesome/react-native-fontawesome/dist/components/FontAwesomeIcon' {
  declare module.exports: any;
}

declare module '@fortawesome/react-native-fontawesome/dist/converter' {
  declare module.exports: any;
}

declare module '@fortawesome/react-native-fontawesome/dist/logger' {
  declare module.exports: any;
}

// Filename aliases
declare module '@fortawesome/react-native-fontawesome/dist/components/FontAwesomeIcon.js' {
  declare module.exports: $Exports<'@fortawesome/react-native-fontawesome/dist/components/FontAwesomeIcon'>;
}
declare module '@fortawesome/react-native-fontawesome/dist/converter.js' {
  declare module.exports: $Exports<'@fortawesome/react-native-fontawesome/dist/converter'>;
}
declare module '@fortawesome/react-native-fontawesome/dist/logger.js' {
  declare module.exports: $Exports<'@fortawesome/react-native-fontawesome/dist/logger'>;
}
declare module '@fortawesome/react-native-fontawesome/index' {
  declare module.exports: $Exports<'@fortawesome/react-native-fontawesome'>;
}
declare module '@fortawesome/react-native-fontawesome/index.js' {
  declare module.exports: $Exports<'@fortawesome/react-native-fontawesome'>;
}
