// flow-typed signature: fe83d674fa65db6c4d89b8b828647fc9
// flow-typed version: <<STUB>>/react-native-screens_v^3.14.0/flow_v0.176.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-screens'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-screens' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-screens/lib/commonjs/createNativeStackNavigator' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/fabric/FullWindowOverlay' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/fabric/FullWindowOverlayNativeComponent' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/fabric' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/fabric/Screen' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/fabric/ScreenContainer' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/fabric/ScreenContainerNativeComponent' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/fabric/ScreenNativeComponent' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/fabric/ScreenNavigationContainer' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/fabric/ScreenNavigationContainerNativeComponent' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/fabric/ScreenStack' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/fabric/ScreenStackHeaderConfigNativeComponent' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/fabric/ScreenStackHeaderSubview' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/fabric/ScreenStackHeaderSubviewNativeComponent' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/fabric/ScreenStackNativeComponent' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/fabric/SearchBar' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/fabric/SearchBarNativeComponent' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/index.native' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/native-stack' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/native-stack/navigators/createNativeStackNavigator' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/native-stack/types' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/native-stack/utils/getDefaultHeaderHeight' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/native-stack/utils/HeaderHeightContext' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/native-stack/utils/SafeAreaProviderCompat' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/native-stack/utils/useBackPressSubscription' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/native-stack/utils/useHeaderHeight' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/native-stack/views/FontProcessor' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/native-stack/views/HeaderConfig' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/native-stack/views/NativeStackView' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/reanimated' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/reanimated/ReanimatedNativeStackScreen' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/reanimated/ReanimatedScreen' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/reanimated/ReanimatedScreenProvider' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/reanimated/ReanimatedTransitionProgressContext' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/reanimated/useReanimatedTransitionProgress' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/TransitionProgressContext' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/types' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/useTransitionProgress' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/commonjs/utils' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/createNativeStackNavigator' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/fabric/FullWindowOverlay' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/fabric/FullWindowOverlayNativeComponent' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/fabric' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/fabric/Screen' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/fabric/ScreenContainer' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/fabric/ScreenContainerNativeComponent' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/fabric/ScreenNativeComponent' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/fabric/ScreenNavigationContainer' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/fabric/ScreenNavigationContainerNativeComponent' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/fabric/ScreenStack' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/fabric/ScreenStackHeaderConfigNativeComponent' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/fabric/ScreenStackHeaderSubview' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/fabric/ScreenStackHeaderSubviewNativeComponent' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/fabric/ScreenStackNativeComponent' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/fabric/SearchBar' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/fabric/SearchBarNativeComponent' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/index.native' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/native-stack' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/native-stack/navigators/createNativeStackNavigator' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/native-stack/types' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/native-stack/utils/getDefaultHeaderHeight' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/native-stack/utils/HeaderHeightContext' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/native-stack/utils/SafeAreaProviderCompat' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/native-stack/utils/useBackPressSubscription' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/native-stack/utils/useHeaderHeight' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/native-stack/views/FontProcessor' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/native-stack/views/HeaderConfig' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/native-stack/views/NativeStackView' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/reanimated' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/reanimated/ReanimatedNativeStackScreen' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/reanimated/ReanimatedScreen' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/reanimated/ReanimatedScreenProvider' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/reanimated/ReanimatedTransitionProgressContext' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/reanimated/useReanimatedTransitionProgress' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/TransitionProgressContext' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/types' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/useTransitionProgress' {
  declare module.exports: any;
}

declare module 'react-native-screens/lib/module/utils' {
  declare module.exports: any;
}

declare module 'react-native-screens/src/fabric/FullWindowOverlay' {
  declare module.exports: any;
}

declare module 'react-native-screens/src/fabric/FullWindowOverlayNativeComponent' {
  declare module.exports: any;
}

declare module 'react-native-screens/src/fabric' {
  declare module.exports: any;
}

declare module 'react-native-screens/src/fabric/Screen' {
  declare module.exports: any;
}

declare module 'react-native-screens/src/fabric/ScreenContainer' {
  declare module.exports: any;
}

declare module 'react-native-screens/src/fabric/ScreenContainerNativeComponent' {
  declare module.exports: any;
}

declare module 'react-native-screens/src/fabric/ScreenNativeComponent' {
  declare module.exports: any;
}

declare module 'react-native-screens/src/fabric/ScreenNavigationContainer' {
  declare module.exports: any;
}

declare module 'react-native-screens/src/fabric/ScreenNavigationContainerNativeComponent' {
  declare module.exports: any;
}

declare module 'react-native-screens/src/fabric/ScreenStack' {
  declare module.exports: any;
}

declare module 'react-native-screens/src/fabric/ScreenStackHeaderConfigNativeComponent' {
  declare module.exports: any;
}

declare module 'react-native-screens/src/fabric/ScreenStackHeaderSubview' {
  declare module.exports: any;
}

declare module 'react-native-screens/src/fabric/ScreenStackHeaderSubviewNativeComponent' {
  declare module.exports: any;
}

declare module 'react-native-screens/src/fabric/ScreenStackNativeComponent' {
  declare module.exports: any;
}

declare module 'react-native-screens/src/fabric/SearchBar' {
  declare module.exports: any;
}

declare module 'react-native-screens/src/fabric/SearchBarNativeComponent' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-screens/lib/commonjs/createNativeStackNavigator.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/createNativeStackNavigator'>;
}
declare module 'react-native-screens/lib/commonjs/fabric/FullWindowOverlay.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/fabric/FullWindowOverlay'>;
}
declare module 'react-native-screens/lib/commonjs/fabric/FullWindowOverlayNativeComponent.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/fabric/FullWindowOverlayNativeComponent'>;
}
declare module 'react-native-screens/lib/commonjs/fabric/index' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/fabric'>;
}
declare module 'react-native-screens/lib/commonjs/fabric/index.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/fabric'>;
}
declare module 'react-native-screens/lib/commonjs/fabric/Screen.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/fabric/Screen'>;
}
declare module 'react-native-screens/lib/commonjs/fabric/ScreenContainer.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/fabric/ScreenContainer'>;
}
declare module 'react-native-screens/lib/commonjs/fabric/ScreenContainerNativeComponent.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/fabric/ScreenContainerNativeComponent'>;
}
declare module 'react-native-screens/lib/commonjs/fabric/ScreenNativeComponent.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/fabric/ScreenNativeComponent'>;
}
declare module 'react-native-screens/lib/commonjs/fabric/ScreenNavigationContainer.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/fabric/ScreenNavigationContainer'>;
}
declare module 'react-native-screens/lib/commonjs/fabric/ScreenNavigationContainerNativeComponent.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/fabric/ScreenNavigationContainerNativeComponent'>;
}
declare module 'react-native-screens/lib/commonjs/fabric/ScreenStack.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/fabric/ScreenStack'>;
}
declare module 'react-native-screens/lib/commonjs/fabric/ScreenStackHeaderConfigNativeComponent.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/fabric/ScreenStackHeaderConfigNativeComponent'>;
}
declare module 'react-native-screens/lib/commonjs/fabric/ScreenStackHeaderSubview.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/fabric/ScreenStackHeaderSubview'>;
}
declare module 'react-native-screens/lib/commonjs/fabric/ScreenStackHeaderSubviewNativeComponent.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/fabric/ScreenStackHeaderSubviewNativeComponent'>;
}
declare module 'react-native-screens/lib/commonjs/fabric/ScreenStackNativeComponent.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/fabric/ScreenStackNativeComponent'>;
}
declare module 'react-native-screens/lib/commonjs/fabric/SearchBar.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/fabric/SearchBar'>;
}
declare module 'react-native-screens/lib/commonjs/fabric/SearchBarNativeComponent.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/fabric/SearchBarNativeComponent'>;
}
declare module 'react-native-screens/lib/commonjs/index' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs'>;
}
declare module 'react-native-screens/lib/commonjs/index.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs'>;
}
declare module 'react-native-screens/lib/commonjs/index.native.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/index.native'>;
}
declare module 'react-native-screens/lib/commonjs/native-stack/index' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/native-stack'>;
}
declare module 'react-native-screens/lib/commonjs/native-stack/index.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/native-stack'>;
}
declare module 'react-native-screens/lib/commonjs/native-stack/navigators/createNativeStackNavigator.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/native-stack/navigators/createNativeStackNavigator'>;
}
declare module 'react-native-screens/lib/commonjs/native-stack/types.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/native-stack/types'>;
}
declare module 'react-native-screens/lib/commonjs/native-stack/utils/getDefaultHeaderHeight.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/native-stack/utils/getDefaultHeaderHeight'>;
}
declare module 'react-native-screens/lib/commonjs/native-stack/utils/HeaderHeightContext.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/native-stack/utils/HeaderHeightContext'>;
}
declare module 'react-native-screens/lib/commonjs/native-stack/utils/SafeAreaProviderCompat.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/native-stack/utils/SafeAreaProviderCompat'>;
}
declare module 'react-native-screens/lib/commonjs/native-stack/utils/useBackPressSubscription.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/native-stack/utils/useBackPressSubscription'>;
}
declare module 'react-native-screens/lib/commonjs/native-stack/utils/useHeaderHeight.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/native-stack/utils/useHeaderHeight'>;
}
declare module 'react-native-screens/lib/commonjs/native-stack/views/FontProcessor.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/native-stack/views/FontProcessor'>;
}
declare module 'react-native-screens/lib/commonjs/native-stack/views/HeaderConfig.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/native-stack/views/HeaderConfig'>;
}
declare module 'react-native-screens/lib/commonjs/native-stack/views/NativeStackView.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/native-stack/views/NativeStackView'>;
}
declare module 'react-native-screens/lib/commonjs/reanimated/index' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/reanimated'>;
}
declare module 'react-native-screens/lib/commonjs/reanimated/index.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/reanimated'>;
}
declare module 'react-native-screens/lib/commonjs/reanimated/ReanimatedNativeStackScreen.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/reanimated/ReanimatedNativeStackScreen'>;
}
declare module 'react-native-screens/lib/commonjs/reanimated/ReanimatedScreen.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/reanimated/ReanimatedScreen'>;
}
declare module 'react-native-screens/lib/commonjs/reanimated/ReanimatedScreenProvider.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/reanimated/ReanimatedScreenProvider'>;
}
declare module 'react-native-screens/lib/commonjs/reanimated/ReanimatedTransitionProgressContext.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/reanimated/ReanimatedTransitionProgressContext'>;
}
declare module 'react-native-screens/lib/commonjs/reanimated/useReanimatedTransitionProgress.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/reanimated/useReanimatedTransitionProgress'>;
}
declare module 'react-native-screens/lib/commonjs/TransitionProgressContext.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/TransitionProgressContext'>;
}
declare module 'react-native-screens/lib/commonjs/types.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/types'>;
}
declare module 'react-native-screens/lib/commonjs/useTransitionProgress.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/useTransitionProgress'>;
}
declare module 'react-native-screens/lib/commonjs/utils.js' {
  declare module.exports: $Exports<'react-native-screens/lib/commonjs/utils'>;
}
declare module 'react-native-screens/lib/module/createNativeStackNavigator.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/createNativeStackNavigator'>;
}
declare module 'react-native-screens/lib/module/fabric/FullWindowOverlay.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/fabric/FullWindowOverlay'>;
}
declare module 'react-native-screens/lib/module/fabric/FullWindowOverlayNativeComponent.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/fabric/FullWindowOverlayNativeComponent'>;
}
declare module 'react-native-screens/lib/module/fabric/index' {
  declare module.exports: $Exports<'react-native-screens/lib/module/fabric'>;
}
declare module 'react-native-screens/lib/module/fabric/index.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/fabric'>;
}
declare module 'react-native-screens/lib/module/fabric/Screen.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/fabric/Screen'>;
}
declare module 'react-native-screens/lib/module/fabric/ScreenContainer.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/fabric/ScreenContainer'>;
}
declare module 'react-native-screens/lib/module/fabric/ScreenContainerNativeComponent.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/fabric/ScreenContainerNativeComponent'>;
}
declare module 'react-native-screens/lib/module/fabric/ScreenNativeComponent.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/fabric/ScreenNativeComponent'>;
}
declare module 'react-native-screens/lib/module/fabric/ScreenNavigationContainer.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/fabric/ScreenNavigationContainer'>;
}
declare module 'react-native-screens/lib/module/fabric/ScreenNavigationContainerNativeComponent.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/fabric/ScreenNavigationContainerNativeComponent'>;
}
declare module 'react-native-screens/lib/module/fabric/ScreenStack.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/fabric/ScreenStack'>;
}
declare module 'react-native-screens/lib/module/fabric/ScreenStackHeaderConfigNativeComponent.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/fabric/ScreenStackHeaderConfigNativeComponent'>;
}
declare module 'react-native-screens/lib/module/fabric/ScreenStackHeaderSubview.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/fabric/ScreenStackHeaderSubview'>;
}
declare module 'react-native-screens/lib/module/fabric/ScreenStackHeaderSubviewNativeComponent.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/fabric/ScreenStackHeaderSubviewNativeComponent'>;
}
declare module 'react-native-screens/lib/module/fabric/ScreenStackNativeComponent.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/fabric/ScreenStackNativeComponent'>;
}
declare module 'react-native-screens/lib/module/fabric/SearchBar.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/fabric/SearchBar'>;
}
declare module 'react-native-screens/lib/module/fabric/SearchBarNativeComponent.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/fabric/SearchBarNativeComponent'>;
}
declare module 'react-native-screens/lib/module/index' {
  declare module.exports: $Exports<'react-native-screens/lib/module'>;
}
declare module 'react-native-screens/lib/module/index.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module'>;
}
declare module 'react-native-screens/lib/module/index.native.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/index.native'>;
}
declare module 'react-native-screens/lib/module/native-stack/index' {
  declare module.exports: $Exports<'react-native-screens/lib/module/native-stack'>;
}
declare module 'react-native-screens/lib/module/native-stack/index.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/native-stack'>;
}
declare module 'react-native-screens/lib/module/native-stack/navigators/createNativeStackNavigator.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/native-stack/navigators/createNativeStackNavigator'>;
}
declare module 'react-native-screens/lib/module/native-stack/types.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/native-stack/types'>;
}
declare module 'react-native-screens/lib/module/native-stack/utils/getDefaultHeaderHeight.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/native-stack/utils/getDefaultHeaderHeight'>;
}
declare module 'react-native-screens/lib/module/native-stack/utils/HeaderHeightContext.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/native-stack/utils/HeaderHeightContext'>;
}
declare module 'react-native-screens/lib/module/native-stack/utils/SafeAreaProviderCompat.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/native-stack/utils/SafeAreaProviderCompat'>;
}
declare module 'react-native-screens/lib/module/native-stack/utils/useBackPressSubscription.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/native-stack/utils/useBackPressSubscription'>;
}
declare module 'react-native-screens/lib/module/native-stack/utils/useHeaderHeight.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/native-stack/utils/useHeaderHeight'>;
}
declare module 'react-native-screens/lib/module/native-stack/views/FontProcessor.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/native-stack/views/FontProcessor'>;
}
declare module 'react-native-screens/lib/module/native-stack/views/HeaderConfig.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/native-stack/views/HeaderConfig'>;
}
declare module 'react-native-screens/lib/module/native-stack/views/NativeStackView.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/native-stack/views/NativeStackView'>;
}
declare module 'react-native-screens/lib/module/reanimated/index' {
  declare module.exports: $Exports<'react-native-screens/lib/module/reanimated'>;
}
declare module 'react-native-screens/lib/module/reanimated/index.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/reanimated'>;
}
declare module 'react-native-screens/lib/module/reanimated/ReanimatedNativeStackScreen.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/reanimated/ReanimatedNativeStackScreen'>;
}
declare module 'react-native-screens/lib/module/reanimated/ReanimatedScreen.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/reanimated/ReanimatedScreen'>;
}
declare module 'react-native-screens/lib/module/reanimated/ReanimatedScreenProvider.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/reanimated/ReanimatedScreenProvider'>;
}
declare module 'react-native-screens/lib/module/reanimated/ReanimatedTransitionProgressContext.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/reanimated/ReanimatedTransitionProgressContext'>;
}
declare module 'react-native-screens/lib/module/reanimated/useReanimatedTransitionProgress.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/reanimated/useReanimatedTransitionProgress'>;
}
declare module 'react-native-screens/lib/module/TransitionProgressContext.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/TransitionProgressContext'>;
}
declare module 'react-native-screens/lib/module/types.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/types'>;
}
declare module 'react-native-screens/lib/module/useTransitionProgress.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/useTransitionProgress'>;
}
declare module 'react-native-screens/lib/module/utils.js' {
  declare module.exports: $Exports<'react-native-screens/lib/module/utils'>;
}
declare module 'react-native-screens/src/fabric/FullWindowOverlay.js' {
  declare module.exports: $Exports<'react-native-screens/src/fabric/FullWindowOverlay'>;
}
declare module 'react-native-screens/src/fabric/FullWindowOverlayNativeComponent.js' {
  declare module.exports: $Exports<'react-native-screens/src/fabric/FullWindowOverlayNativeComponent'>;
}
declare module 'react-native-screens/src/fabric/index' {
  declare module.exports: $Exports<'react-native-screens/src/fabric'>;
}
declare module 'react-native-screens/src/fabric/index.js' {
  declare module.exports: $Exports<'react-native-screens/src/fabric'>;
}
declare module 'react-native-screens/src/fabric/Screen.js' {
  declare module.exports: $Exports<'react-native-screens/src/fabric/Screen'>;
}
declare module 'react-native-screens/src/fabric/ScreenContainer.js' {
  declare module.exports: $Exports<'react-native-screens/src/fabric/ScreenContainer'>;
}
declare module 'react-native-screens/src/fabric/ScreenContainerNativeComponent.js' {
  declare module.exports: $Exports<'react-native-screens/src/fabric/ScreenContainerNativeComponent'>;
}
declare module 'react-native-screens/src/fabric/ScreenNativeComponent.js' {
  declare module.exports: $Exports<'react-native-screens/src/fabric/ScreenNativeComponent'>;
}
declare module 'react-native-screens/src/fabric/ScreenNavigationContainer.js' {
  declare module.exports: $Exports<'react-native-screens/src/fabric/ScreenNavigationContainer'>;
}
declare module 'react-native-screens/src/fabric/ScreenNavigationContainerNativeComponent.js' {
  declare module.exports: $Exports<'react-native-screens/src/fabric/ScreenNavigationContainerNativeComponent'>;
}
declare module 'react-native-screens/src/fabric/ScreenStack.js' {
  declare module.exports: $Exports<'react-native-screens/src/fabric/ScreenStack'>;
}
declare module 'react-native-screens/src/fabric/ScreenStackHeaderConfigNativeComponent.js' {
  declare module.exports: $Exports<'react-native-screens/src/fabric/ScreenStackHeaderConfigNativeComponent'>;
}
declare module 'react-native-screens/src/fabric/ScreenStackHeaderSubview.js' {
  declare module.exports: $Exports<'react-native-screens/src/fabric/ScreenStackHeaderSubview'>;
}
declare module 'react-native-screens/src/fabric/ScreenStackHeaderSubviewNativeComponent.js' {
  declare module.exports: $Exports<'react-native-screens/src/fabric/ScreenStackHeaderSubviewNativeComponent'>;
}
declare module 'react-native-screens/src/fabric/ScreenStackNativeComponent.js' {
  declare module.exports: $Exports<'react-native-screens/src/fabric/ScreenStackNativeComponent'>;
}
declare module 'react-native-screens/src/fabric/SearchBar.js' {
  declare module.exports: $Exports<'react-native-screens/src/fabric/SearchBar'>;
}
declare module 'react-native-screens/src/fabric/SearchBarNativeComponent.js' {
  declare module.exports: $Exports<'react-native-screens/src/fabric/SearchBarNativeComponent'>;
}
