// flow-typed signature: 786871958dfe2676de6308055c695504
// flow-typed version: <<STUB>>/react-native-ble-manager_v^8.4.1/flow_v0.176.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-ble-manager'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-ble-manager' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-ble-manager/BleManager' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-ble-manager/BleManager.js' {
  declare module.exports: $Exports<'react-native-ble-manager/BleManager'>;
}
